### PR TITLE
Light/Dark Mode Fix

### LINKED ISSUE #36: Dark/Light Mode
### Description
There is a dark/light mode solution in the app, but it is not fully functioning. It is based on the shpeito's device's UI theme and when toggling, it takes the shpeito back to the login screen.

### Solution
Add an option in the profile page for Light Mode / Dark Mode following the Figma design. Keep consistency by labeling the colors with Color_Light or Color_Dark. 

Make sure the colors change appropriately based on the Figma designs too.

### Severity
High

### Environment
OS: Android 5.1
App Version: Beta
Device: Any Android Device

### PR DESCRIPTION
**Pull request by d-dovale**
### Summary
---
- Added new UI on the `StaticProfilePage.kt` through the `AppearanceToggle` and `ModeButton` functions for the dark mode and light mode buttons which match the Figma design
	- 

- Imported the corresponding icons needed in the res/drawable folder for the Appearance Toggle along with the light mode gator to fix the positioning of the gator on the Profile Page
- Added Light Mode/Dark Mode functionality to the `AppearanceToggle` 
	- This was done by introducing a `isDarkMode` variable which is part of the `UserState` which allows the app to toggle to dark mode/light mode
	- We then had to pass in `isDarkMode` to our Composable functions

### Reference
---
- [Asana Link](https://app.asana.com/0/1205340802626919/1208493484282661/f)

### Extra
---
- Additionally, we made changes on the Points Page to match the Figma design such as altering the Semester Percentile Bars in the `PointsPercentile` function to match Figma designs

### CODE REVIEW

**Comment by TheAndreiUrsu** [comment]
Looks good, could you change the branch to merge to from **main** to **develop**?

**Comment by TheAndreiUrsu** [comment]
LGTM, Awesome work guys!!

**Comment by d-dovale** [comment]
Thanks 😄

**Review by TheAndreiUrsu — APPROVED** [review]
I approve, waiting for Anthony to approve.

**Review by Anthony-Zurita — APPROVED** [review]
Hey @JakeWesta and @d-dovale, great job boys on this! Looks great, I appreciate the name changing on the query and in other places to make the code more readable.

**Pull request merged**
